# Site settings
title: 而已。
tag_text: 而已。
description: A responsive template for publishing single-page websites, articles that are easy on the eyes
url: "http://bobmemo.github.io"
baseurl: ""

paginate: 3

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]

plugins:
  - jekyll-feed
